# Generated by Django 5.1.15 on 2026-06-03 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("place", "Place"),
                            ("talent", "Talent"),
                            ("community", "Community"),
                            ("brand", "Brand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("handle", models.CharField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("tagline", models.CharField(blank=True, max_length=240)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("instagram", models.CharField(blank=True, max_length=120)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-follower_count", "display_name"],
            },
        ),
    ]
