# Generated by Django 5.1.15 on 2026-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
