# Generated by Django 5.1.15 on 2026-06-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("flyer_url", models.URLField(blank=True)),
                ("date", models.DateField()),
                ("start_time", models.CharField(max_length=40)),
                ("end_time", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("vibe_tags", models.JSONField(blank=True, default=list)),
                ("music_tags", models.JSONField(blank=True, default=list)),
                (
                    "cover_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("age_restriction", models.CharField(blank=True, max_length=20)),
                ("going_count", models.PositiveIntegerField(default=0)),
                ("interested_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hosts",
                    models.ManyToManyField(
                        blank=True, related_name="events_hosted", to="profiles.profile"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_at_venue",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("redeemed", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("remaining", models.PositiveIntegerField(blank=True, null=True)),
                ("perks", models.JSONField(blank=True, default=list)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_options",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
