# Generated by Django 5.1.15 on 2026-06-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="required_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "Guest"),
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("gold", "Gold"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="deal",
            name="success_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="success_message",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="deal",
            name="total_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="venue",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="commit_required_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "Guest"),
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("gold", "Gold"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="commitment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None (save only)"),
                    ("rsvp", "RSVP"),
                    ("ticket", "Ticket"),
                    ("external", "External"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="event",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="issued_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="passcode_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("passcode", "Passcode"),
                    ("member", "Member"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ticketoption",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ticketoption",
            name="is_member_exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketoption",
            name="required_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "Guest"),
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("gold", "Gold"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DealOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("image", models.URLField(blank=True)),
                ("limit_per_user", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "required_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("guest", "Guest"),
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="events.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                ("rotates_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_codes",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
