# Generated by Django 5.1.15 on 2026-06-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_tier",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("gold", "Gold"),
                ],
                default="free",
                max_length=10,
            ),
        ),
    ]
