# Generated by Django 5.1.15 on 2026-06-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_deal_required_tier_deal_subtitle_deal_success_image_and_more"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ownedticket",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="entry_instructions",
            field=models.CharField(
                default="Show this pass at the door.", max_length=240
            ),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="holder_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="kind",
            field=models.CharField(
                choices=[("rsvp", "RSVP"), ("ticket", "Ticket"), ("member", "Member")],
                default="ticket",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="ownedticket",
            name="qr_value",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ownedticket",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_tickets",
                to="events.ticketoption",
            ),
        ),
        migrations.AlterField(
            model_name="ownedticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("valid", "Valid"),
                    ("checked_in", "Checked in"),
                    ("refunded", "Refunded"),
                    ("voided", "Voided"),
                ],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("venue", models.CharField(blank=True, max_length=160)),
                ("image", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("redeemed", "Redeemed"), ("voided", "Voided")],
                        default="redeemed",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=32)),
                ("holder_name", models.CharField(blank=True, max_length=160)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="events.deal",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="events.event",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="events.dealoffer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
    ]
