# Generated by Django 5.1.15 on 2026-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_backfill_pass_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownedticket",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
